HOCS-2457 add description label to Swagger service
UKHomeOffice/hocs-info-service pull request #277
Opened 2021-04-01 13:02 UTC by abarker66

This ticket updates the identifying label on the existing Swagger service on info service. 

The Swagger page is available at http://localhost:8085/swagger-ui.html

2021-04-06 10:45 UTC, robertdeniszczyc2 approved these changes
Looks good to me

2021-04-06 11:09 UTC, robertdeniszczyc2 requested changes
Just noticed on the ticket it mentions functionality requires retrofitting to info service to ensure that this isn't available on prod. Has this acceptance criteria being covered here?

Thanks,
Rob

2021-04-13 14:25 UTC, abarker66 commented
Spring profile switching is now added. The profile is 'swagger' and can be added as an env variable or as a -D JVM command line option. So without the 'swagger' profile there will be no swagger endpoints available.

2021-04-13 15:41 UTC, robertdeniszczyc2 approved these changes

2021-04-13 15:52 UTC, merged