HOCS-2755 - MUI Team Management - Re-De/activate a team
UKHomeOffice/hocs-info-service pull request #303
Opened 2021-06-18 08:47 UTC by agraham19

* Add functionality to existing patch endpoint to active/deactivate team

2021-06-18 12:28 UTC, fewtrees-ho requested changes
Thanks Andy :-)

Looks good, just minor suggestions made.

.DS_Store needs to be removed from the commit. It's in .gitignore but somehow made it past!

The approval is pending the High change only.

2021-06-24 08:22 UTC, agraham19 commented on src/main/java/uk/gov/digital/ho/hocs/info/api/TeamService.java
> +    public void setTeamActiveFlag(UUID teamUUID, boolean active) {
I have addressed this.

2021-06-24 08:22 UTC, agraham19 commented on src/test/java/uk/gov/digital/ho/hocs/info/api/TeamResourceTest.java
> +    @Test
I have addressed this.

2021-06-24 08:22 UTC, agraham19 commented on src/main/java/uk/gov/digital/ho/hocs/info/api/TeamResource.java
> +        if (teamActiveFlagHasChanged(team, teamPatch)) {
I have addressed this.

2021-06-24 08:32 UTC, fewtrees-ho approved these changes
Thanks :-)

2021-07-01 13:23 UTC, merged